baseURL = "https://diacircuitpython.org/"
languageCode = "en"
title = "Día CircuitPython 2020"
DefaultContentLanguage = "es"
# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
disableLanguages = ["fr", "en"]

[params]
    title = "Día CircuitPython 2020"
    date = "2020-09-09"
    description = "El Día de CircuitPython, es cuando celebramos todas las cosas que tienen que ver con este maravilloso lenguaje de programación y su comunidad. Talleres, tutoriales y espacios para mostrar tus proyectos con CircuitPython."
    images = ["/images/social-share.jpg"]
    email = "info@diacircuitpython.org"
    keywords = "programación, circuitpython, quetzalblinka, python, adafruit"
    copyright = "CC-BY"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"

[menu]
#[[menu.main]]
#    identifier = "jobs"
#    name = "Jobs"
#    url = "https://jobs.devfesttoulouse.fr/"
#    weight = 200
#    external = true

[languages]
[languages.es]
    weight = 1
    languageName = "es"

[languages.en]
    weight = 2
    languageName = "gb"

[languages.fr]
    weight = 3
    languageName = "fr"

[languages.es.params]
    description = "El Día CircuitPython es para poder celebrar a este lenguaje y a su comunidad, pero en nuestro idioma"


[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
